Issue #47 - Criar passeio automático
Corollarium/lajevr pull request #57
Opened 2022-01-05 21:19 UTC by hiperlogic

Codificado métodos para Tour Automático e os processos para iniciar, pausar e retomar.

Cria caminho para câmera (obtido do Blender)
Inicia animação
Pausa/retoma animação
Cancela animação (não chamado... ainda)
DOM com os callbacks no teclado (espaço) e ícone (botão canto inferior direito)

2022-01-06 13:55 UTC, brunobg requested changes
eu toquei a animação.
- o caminho em geral está ótimo. a velocidade também tá boa, bem parecida com o que é um mergulho. Imagino que voê vai colocar os boids em algum ponto do meio da animação (o normal é eles ficarem mais perto da ilha, não ficam na areia)
- mas ela não está smooth. parece piecewiese linear em vez de uma linha contínua, fica de soquinho. precisa deixar smooth.
- quase não se olha pra cima em mergulho. só a hora que você vai subir. em geral você tá olhando para frente ou baixo, ou seja, câmera em direção pra baixo do plano horizontal. O motivo é anatômico, você tá sempre em posição de natação, com o corpo para baixo.
- a câmera parece algumas vezes inclinada 45 graus também. 
 
se vc quiser ver com o mar perfeito faça um rebase em cima do https://github.com/Corollarium/lajevr/commit/120b6c66789cb5f4aa7441b8f9c2a98233600187.

2022-01-06 13:55 UTC, brunobg commented on components/Underwaterb.vue
> +    this.animTour = this.createPathForAnimation(this.camera, tourCurve, 60);
faltou declarar na classe

2022-01-06 13:55 UTC, brunobg commented on components/Underwaterb.vue
> +    stopGuidedTour () {
nunca é chamada

2022-01-06 13:55 UTC, brunobg commented on components/Underwaterb.vue
> +      if (!this.underwater.animTour) {
não entendo esta lógica, pq seria null e pq sendo null o playing vira true?

2022-01-06 13:55 UTC, brunobg commented on components/Underwaterb.vue
> +  <div id="underwater" v-on:keyup.32="toggleGuidedTour">
32 é espaço? podia ter um help naquele texto que você mexeu no outro pr.

2022-01-06 13:55 UTC, brunobg commented on components/Underwaterb.vue
> +    if (this.animTour) {
pq isso estaria não inicializado? não é melhor já criar esta animação na criação da cena? menos chance de chabu.

2022-01-06 13:55 UTC, brunobg commented on components/Underwaterb.vue
> +    this.animTour = null;
aqui também, não precisaria dar null.

2022-01-06 13:55 UTC, brunobg commented on components/Underwaterb.vue
> +      playing: false,
talvez você possa fazer um `computed` que leia direto o `animTour._paused`? evita replicar estado e ter que syncar.

2022-01-06 14:14 UTC, hiperlogic commented on components/Underwaterb.vue
> +      if (!this.underwater.animTour) {
é pq pensei no stop. Que acabei não implementando... mas tinha outro motivo... que tenho que rever

2022-01-07 08:01 UTC, hiperlogic commented on components/Underwaterb.vue
> +    this.animTour = this.createPathForAnimation(this.camera, tourCurve, 60);
Declarar o que na classe? O "animTour"?

2022-01-07 08:01 UTC, hiperlogic commented on components/Underwaterb.vue
> +    stopGuidedTour () {
Eu coloquei para caso haja a necessidade de chamar uma parada geral da animação.

2022-01-07 08:02 UTC, hiperlogic commented on components/Underwaterb.vue
> +  <div id="underwater" v-on:keyup.32="toggleGuidedTour">
32 é espaço... eu tentei colocar o @keyup.space=... mas não funcionou aqui... dessa forma funcionou

2022-01-07 08:04 UTC, hiperlogic commented on components/Underwaterb.vue
> +    if (this.animTour) {
da forma como está, a animação é criada e tocada. Não corri atrás do código apenas para cria-la... 
A preocupação inicial foi criar uma animação correta, então o design do passeio me tomou muito tempo.
animTour nulo significa que a animação nunca foi executada ou que ela foi interrompida (com o quitAnimation)

2022-01-07 08:06 UTC, hiperlogic commented on components/Underwaterb.vue
> +      playing: false,
O problema é o animTour inicial ser nulo. (vide comentário anterior, no pauseTour.

2022-01-07 08:10 UTC, hiperlogic commented
- Câmera 45 graus foi arrumada
- O smoothness está no processo de velocidade por segmentos entre pontos da curva. Ajustei o processo de criação da curva com um multiplicador para adicionar mais segmentos. Ao adicionar mais segmentos deve ser necessário ajustar a velocidade da animação.
- Infelizmente o processo de pathfollowing está na câmera. Uma estratégia mais adequada para um passeio seria criar um track, não uma curva. E ainda assim eu não tenho certeza que o track diretamente na câmera seria adequado. Talvez colocar a câmera como filho do objeto que segue o track e limitar a movimentação da câmera seria mais adequado. Outra solução é criarmos outras animações no blender e exportarmos as animações para carregarmos diretamente no Babylon, usando os baking e VAT.

2022-01-07 19:19 UTC, hiperlogic commented on components/Underwaterb.vue
> +      if (!this.underwater.animTour) {
animTour é a animação, o toggle serve para o pause. Enquanto a animação não é requisitada, ela é inexistente. Por isso a verificação de se é existente. Se ela não existe, então ajuste o playing para true logo após o toggle, para garantir que não haja imprevistos.

2022-01-07 19:20 UTC, hiperlogic commented on components/Underwaterb.vue
> +    this.animTour = null;
A intenção foi a de liberar memória (na passada seguinte do GC). Se quiser, removo a linha.

2022-01-07 21:06 UTC, brunobg commented on components/Underwaterb.vue
> +    this.animTour = null;
A não ser que esteja usando gigabytes de RAM, acho melhor já inicializar tudo de uma vez, por favor.

2022-01-07 22:31 UTC, brunobg commented
Review:
- o debug das bolinhas e linhas foi ótimo
- o smooth tá perfeito
- única sugestão de mudança: o caminho passa bem do lado do moreia no começo, podia passar por cima dele pra poder ver melhor. Só transladar mesmo. Pode até mudar o modelo do moreia de lugar se for facilitar, ele tá já "mais ou menos no lugar mesmo. Ou talvez melhor ainda, podia transladar o caminho e o moreia pra ficar mais perto da ilha. Na realidade ele está mais perto que isso, e aí dá pra ver as pedras da lateral que atualmetne é impossível de ver pq está muito distante. Vai ajudar também quando vc colocar os volumes dos boids, e os peixes costumam ficar ali perto das pedras. Se quiser abrimos um call pra posicionar o modelo direito no blender, isso é minha culpa pq eu coloquei ele meio no olho.
- e deixe já a animação criada do início que evita os problemas de null, fazendo isso tá aprovado e fechado

2022-01-09 00:33 UTC, hiperlogic commented on components/Underwaterb.vue
> +    if (this.animTour) {
Inicializado... mas mantive o if para qualquer caso...

2022-01-09 00:33 UTC, hiperlogic commented on components/Underwaterb.vue
> +      playing: false,
Ficou computed...

2022-01-09 00:34 UTC, hiperlogic commented on components/Underwaterb.vue
> +      if (!this.underwater.animTour) {
animTour foi inicializado no bootScene, mas deixei a verificação para caso de algo estranho acontecer...

2022-01-09 00:36 UTC, hiperlogic commented
A giradinha no início é por causa do path e da câmera... as curvas tem que ser realizadas no mesmo plano ortonormal ou a câmera ficará inclinada... e pra arrumar é um trampo... o que complica rearrumar o caminho para passar pelo moreia por agora...

2022-01-10 15:57 UTC, brunobg approved these changes
Ok, estou aprovando e depois vejo este problema da giradinha inicial. Quando vc der um rebase e acertar os conflitos dou merge.

2022-01-10 19:27 UTC, merged